version: "2.32.1"
name: Bioinformatics_pipeline
services:
  canu_Assembly:
    image: staphb/canu:2.2
    volumes:
      - /home/share/SAMN15455050/:/data/:rw
    command: |
        canu genomeSize=3.2m -p canu -d canu -pacbio /data/raw_data/Pacbio/SRR12159828.fastq.gz

  canu_Trim:
    image: staphb/canu:2.2
    volumes:
      - /home/share/SAMN15455050/:/data/:rw
    command: |
        canu genomeSize=3.2m -p canu -d canu correctedErrorRate=0.015 -trimmed -corrected -pacbio /data/raw_data/Pacbio/SRR12159828.fastq.gz
    depends_on:
      canu_Assembly:
        condition: service_completed_successfully

  # quast_assembly_evaluation:
  #   image: staphb/quast:5.3.0
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       quast.py
  #   depends_on:
  #     canu_Trim:
  #       condition: service_completed_successfully

# ./quast.py test_data/contigs_1.fasta \
#            test_data/contigs_2.fasta \
#         -r test_data/reference.fasta.gz \
#         -g test_data/genes.txt \
#         -1 test_data/reads1.fastq.gz -2 test_data/reads2.fastq.gz \
#         -o quast_test_output

  # busco_Benchmarking:
  #   image: staphb/busco:5.8.2
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       busco -i genome.fna
  #   depends_on:
  #     canu_Trim:
  #       condition: service_completed_successfully


  # build_bwa_index:
  #   image: staphb/bwa:0.7.18
  #   volumes:
  #     - /home/share/SAMN15455050/RefSeq/GCF_009913655.1/:/data/:rw
  #   command: |
  #       bwa index -p GCF_009913655.1 GCF_009913655.1.fna 
  #   depends_on:
  #     canu_Trim:
  #       condition: service_completed_successfully
  
  # build_bwa_folder:
  #   image: staphb/bwa:0.7.18
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       mkdir -p bwa
  
  # bwa_mem:
  #   image: staphb/bwa:0.7.18
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       bwa mem -t 4 RefSeq/GCF_009913655.1/GCF_009913655.1 ./canu/canu.contigs.fasta -o ./bwa/SAMN15455050.sam
  # #      bwa mem -t 4 RefSeq/GCF_009913655.1/GCF_009913655.1 ./raw_data/Pacbio/SRR12159828.fastq.gz -o ./bwa/SAMN15455050.raw.sam
  #   depends_on:
  #     build_bwa_folder:
  #       condition: service_completed_successfully


  # samtools_extracting_map_reads:
  #   image: staphb/samtools:1.21
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       mkdir -p samtools; 
  #       time samtools fastq -@ 4 -F 4 ./bwa/SAMN15455050.sam > ./samtools/SAMN15455050.map.fq 
  #   depends_on:
  #     bwa_mem:
  #       condition: service_completed_successfully



  # spades_Assembly:
  #   image: staphb/spades:4.0.0
  #   volumes:
  #     - /home/share/SAMN15455050/:/data/:rw
  #   command: |
  #       bin/spades.py -1 left.fastq.gz -2 right.fastq.gz -o output_folder
  #   depends_on:
  #     samtools_extracting_map_reads:
  #       condition: service_completed_successfully



  prokka_Annotation:
    image: staphb/prokka:1.14.6
    volumes:
      - /home/share/SAMN15455050/:/data/:rw
    command: |
        prokka \
          --outdir ./prokka/SAMN15455050 --force \
          --prefix SAMN15455050 --addgenes --locustag LAP \
          --increment 10 \
          --gffver 3 \
          --centre tig0000000 --compliant \
          --genus Lactiplantibacillus --species plantarum \
          --kingdom Bacteria --gcode 11 --usegenus \
          --proteins /opt/prokka/db/trusted/Ecocyc-17.6 \
          --evalue 1e-9 --rfam \
          --cpus 4 \
          ./canu/canu.contigs.fasta
    depends_on:
      canu_Trim:
        condition: service_completed_successfully
